#include<bits/stdc++.h>
using namespace std;

int main()
{
    int t,n,j,i,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,a,num;
    scanf("%d",&t);
    for(i=1;i<=t;i++)
    {
        scanf("%d",&n);
        c0=0;
        c1=0;
        c2=0;
        c3=0;
        c4=0;
        c5=0;
        c6=0;
        c7=0;
        c8=0;
        c9=0;
        for(j=1;j<=n;j++)
        {
            num=j;
            while(num!=0)
            {
                a=num%10;
                num=num/10;
                if(a==0)
                {
                    c0++;
                }
                if(a==1)
                {
                    c1++;
                }
                if(a==2)
                {
                    c2++;
                }
                if(a==3)
                {
                    c3++;
                }
                if(a==4)
                {
                    c4++;
                }
                if(a==5)
                {
                    c5++;
                }
                if(a==6)
                {
                    c6++;
                }
                if(a==7)
                {
                    c7++;
                }
                if(a==8)
                {
                    c8++;
                }
                if(a==9)
                {
                    c9++;
                }
            }
        }
        printf("%d %d %d %d %d %d %d %d %d %d\n",c0,c1,c2,c3,c4,c5,c6,c7,c8,c9);
    }
    return 0;
}
